### ISSUE TITLE
Propozycja użycia Hive zamiast Flutter secure storage

### ISSUE THREAD

**Issue by gawi151** [wspieramprzyrode/mobile#3]
Propozycja jest taka aby zastąpić https://pub.dev/packages/flutter_secure_storage na https://pub.dev/packages/hive.

Flutter secure storage działa tylko na Android i iOS.

Hive jest czysto dartową implementacją -> nie zawiera kodu dla platform i działa na wszystkim mobilka i browser.

**Comment by wwojcik** [comment]
great - removed secure-storage added hive
